name: Arduino Code Build Check

on:
  push:
    branches:
      - main 
  pull_request:
    branches: [ main ]

jobs:
  pi-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
        with:
          submodules: recursive
      - name: Set up system
        run: python3 scripts/setup.py --skip-upgrade
      - name: Ensure Arduino Code Builds
        run: python3 scripts/build_arduino.py
